package cli

// Commands
const (
	CmdAbort         = "ABORT"
	CmdAppend        = "APPEND"
	CmdAuth          = "AUTH"
	CmdBFAdd         = "BF.ADD"
	CmdBFExists      = "BF.EXISTS"
	CmdBFInfo        = "BF.INFO"
	CmdBFReserve     = "BF.RESERVE"
	CmdBGRewriteAOF  = "BGREWRITEAOF"
	CmdBitCount      = "BITCOUNT"
	CmdBitField      = "BITFIELD"
	CmdBitOp         = "BITOP"
	CmdBitFieldRO    = "BITFIELD_RO"
	CmdBitPos        = "BITPOS"
	CmdClient        = "CLIENT"
	CmdCommand       = "COMMAND"
	CmdCopy          = "COPY"
	CmdDBSize        = "DBSIZE"
	CmdDecr          = "DECR"
	CmdDecrBy        = "DECRBY"
	CmdDel           = "DEL"
	CmdDiscard       = "DISCARD"
	CmdDump          = "DUMP"
	CmdEcho          = "ECHO"
	CmdExec          = "EXEC"
	CmdExists        = "EXISTS"
	CmdExpire        = "EXPIRE"
	CmdExpireAt      = "EXPIREAT"
	CmdExpireTime    = "EXPIRETIME"
	CmdFlushDB       = "FLUSHDB"
	CmdGeoAdd        = "GEOADD"
	CmdGeoDist       = "GEODIST"
	CmdGet           = "GET"
	CmdGetBit        = "GETBIT"
	CmdGetDel        = "GETDEL"
	CmdGetEx         = "GETEX"
	CmdGetRange      = "GETRANGE"
	CmdGetSet        = "GETSET"
	CmdHDel          = "HDEL"
	CmdHello         = "HELLO"
	CmdHExists       = "HEXISTS"
	CmdHGet          = "HGET"
	CmdHGetAll       = "HGETALL"
	CmdHIncrBy       = "HINCRBY"
	CmdHIncrByFloat  = "HINCRBYFLOAT"
	CmdHKeys         = "HKEYS"
	CmdHLen          = "HLEN"
	CmdHMGet         = "HMGET"
	CmdHMSet         = "HMSET"
	CmdHRandField    = "HRANDFIELD"
	CmdHScan         = "HSCAN"
	CmdHSet          = "HSET"
	CmdHSetNX        = "HSETNX"
	CmdHStrLen       = "HSTRLEN"
	CmdHVals         = "HVALS"
	CmdIncr          = "INCR"
	CmdIncrBy        = "INCRBY"
	CmdIncrByFloat   = "INCRBYFLOAT"
	CmdInfo          = "INFO"
	CmdJSONArrAppend = "JSON.ARRAPPEND"
	CmdJSONArrInsert = "JSON.ARRINSERT"
	CmdJSONArrLen    = "JSON.ARRLEN"
	CmdJSONArrPop    = "JSON.ARRPOP"
	CmdJSONArrTrim   = "JSON.ARRTRIM"
	CmdJSONClear     = "JSON.CLEAR"
	CmdJSONDebug     = "JSON.DEBUG"
	CmdJSONDel       = "JSON.DEL"
	CmdJSONForget    = "JSON.FORGET"
	CmdJSONGet       = "JSON.GET"
	CmdJSONIngest    = "JSON.INGEST"
	CmdJSONMGet      = "JSON.MGET"
	CmdJSONNumIncrBy = "JSON.NUMINCRBY"
	CmdJSONNumMultBy = "JSON.NUMMULTBY"
	CmdJSONObjKeys   = "JSON.OBJKEYS"
	CmdJSONObjLen    = "JSON.OBJLEN"
	CmdJSONResp      = "JSON.RESP"
	CmdJSONSet       = "JSON.SET"
	CmdJSONStrLen    = "JSON.STRLEN"
	CmdJSONStrAppend = "JSON.STRAPPEND"
	CmdJSONToggle    = "JSON.TOGGLE"
	CmdJSONType      = "JSON.TYPE"
	CmdKeys          = "KEYS"
	CmdLatency       = "LATENCY"
	CmdLLen          = "LLEN"
	CmdLPop          = "LPOP"
	CmdLPush         = "LPUSH"
	CmdLRU           = "LRU"
	CmdMGet          = "MGET"
	CmdMSet          = "MSET"
	CmdMulti         = "MULTI"
	CmdObject        = "OBJECT"
	CmdPersist       = "PERSIST"
	CmdPFAdd         = "PFADD"
	CmdPFCount       = "PFCOUNT"
	CmdPFMerge       = "PFMERGE"
	CmdPing          = "PING"
	CmdPTTL          = "PTTL"
	CmdQUnwatch      = "Q.UNWATCH"
	CmdQWatch        = "Q.WATCH"
	CmdRename        = "RENAME"
	CmdRestore       = "RESTORE"
	CmdRPop          = "RPOP"
	CmdRPush         = "RPUSH"
	CmdSAdd          = "SADD"
	CmdSCard         = "SCARD"
	CmdSDiff         = "SDIFF"
	CmdSelect        = "SELECT"
	CmdSet           = "SET"
	CmdSetBit        = "SETBIT"
	CmdSetEx         = "SETEX"
	CmdSInter        = "SINTER"
	CmdSleep         = "SLEEP"
	CmdSMembers      = "SMEMBERS"
	CmdSRem          = "SREM"
	CmdSubscribe     = "SUBSCRIBE"
	CmdTouch         = "TOUCH"
	CmdTTL           = "TTL"
	CmdType          = "TYPE"
	CmdUnsubscribe   = "UNSUBSCRIBE"
	CmdZAdd          = "ZADD"
	CmdZRange        = "ZRANGE"
	CmdZPopMin       = "ZPOPMIN"
	CmdZRank         = "ZRANK"
)

// Various constants
const (
	SuffixWatch   = ".WATCH"
	SuffixUnwatch = ".UNWATCH"
)

var dicedbCommands = []string{
	CmdAbort, CmdAppend, CmdAuth, CmdBFAdd, CmdBFExists, CmdBFInfo, CmdBFReserve, CmdBGRewriteAOF, CmdBitCount, CmdBitField,
	CmdBitOp, CmdBitFieldRO, CmdBitPos, CmdClient, CmdCommand, CmdCopy, CmdDBSize, CmdDecr, CmdDecrBy, CmdDel,
	CmdDiscard, CmdDump, CmdEcho, CmdExec, CmdExists, CmdExpire, CmdExpireAt, CmdExpireTime, CmdFlushDB, CmdGeoAdd,
	CmdGeoDist, CmdGet, CmdGetBit, CmdGetDel, CmdGetEx, CmdGetRange, CmdGetSet, CmdHDel, CmdHello, CmdHExists,
	CmdHGet, CmdHGetAll, CmdHIncrBy, CmdHIncrByFloat, CmdHKeys, CmdHLen, CmdHMGet, CmdHMSet, CmdHRandField, CmdHScan,
	CmdHSet, CmdHSetNX, CmdHStrLen, CmdHVals, CmdIncr, CmdIncrBy, CmdIncrByFloat, CmdInfo, CmdJSONArrAppend, CmdJSONArrInsert,
	CmdJSONArrLen, CmdJSONArrPop, CmdJSONArrTrim, CmdJSONClear, CmdJSONDebug, CmdJSONDel, CmdJSONForget, CmdJSONGet, CmdJSONIngest, CmdJSONMGet,
	CmdJSONNumIncrBy, CmdJSONNumMultBy, CmdJSONObjKeys, CmdJSONObjLen, CmdJSONResp, CmdJSONSet, CmdJSONStrLen, CmdJSONStrAppend, CmdJSONToggle, CmdJSONType,
	CmdKeys, CmdLatency, CmdLLen, CmdLPop, CmdLPush, CmdLRU, CmdMGet, CmdMSet, CmdMulti, CmdObject,
	CmdPersist, CmdPFAdd, CmdPFCount, CmdPFMerge, CmdPing, CmdPTTL, CmdQUnwatch, CmdQWatch, CmdRename, CmdRestore,
	CmdRPop, CmdRPush, CmdSAdd, CmdSCard, CmdSDiff, CmdSelect, CmdSet, CmdSetBit, CmdSetEx, CmdSInter,
	CmdSleep, CmdSMembers, CmdSRem, CmdSubscribe, CmdTouch, CmdTTL, CmdType, CmdZAdd, CmdZRange, CmdZPopMin,
	CmdZRank,
}
